<?php

/**
 * Include batch.inc when module loads.  Required for batch processing!
 */
function icg_csv_import_ui_init() {
//  module_load_include('inc', 'icg_csv_import', 'includes/batch');

  // Turn on error reporting.
  error_reporting(E_ALL);
  ini_set('display_errors', TRUE);
  ini_set('display_startup_errors', TRUE);
}

/**
 * Impl. hook_xml_form_builder_get_form_modify_definition
 *
 * Cause we gonna modify some definitions, if you know what I mean.
 *
 * @param $form
 * @param $form_state
 *
 */
function icg_csv_import_ui_xml_form_builder_get_form_modify_definition_alter(&$form, &$form_state) {
  // Since we're using a global, we'll just assert it's not empty.
  global $_icg_csv_import_ui_glob;

  if (empty($_icg_csv_import_ui_glob)) {
    return;
  }

  // @TODO learn objective forms.
  // @Follow-up thought: no thanks.

  //We'll iterate our form and change manipulable fields to our liking.
  _icg_form_array_iterator_set_options_redux($form);
}

/**
 * ICG CSV Import Menu
 *
 * @return array
 */
function icg_csv_import_ui_menu() {
  $items = array();
  $items['islandora/object/%islandora_object/manage/csv-import'] = array(
    'title' => t('CSV Import'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('icg_csv_import_ui_form', 2),
    'access arguments' => array(2),
    'access callback' => 'icg_csv_access_callback',
    'file' => 'includes/map_ingest_form.inc',
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

/**
 * ICG CSV Menu Item Access Callback
 */
function icg_csv_access_callback($object) {
  if (user_access('ingest fedora objects')) {
    $relation = '';
    $collection_models = islandora_basic_collection_get_collection_content_models();
    $collection_predicates = array(
      'isMemberOfCollection',
      'isMemberOf',
    );
    $is_a_collection = count(array_intersect($collection_models, $object->models)) > 0;
    return $is_a_collection;
  }
  return FALSE;
}
